### ISSUE TITLE
exercise 9.2.4: cell_coords_to_polygons function inputs

### ISSUE THREAD

**Issue by hzille** [abjer/tsds#24]
Hi everyone. We are really struggling with exercise 9.2.4. of the current assignment. We couldn't figure out what exactly the inputs for the cell_coords_to_polygons should be. In particular, square.df, x, and y. Does anyone have an idea for that one?

Thanks in advance!

**Comment by abjer** [comment]
You want to make a loop over the boundary of east and north (i.e. x and y) with 500m apart. This should be inserted into a dataframe which may look something like this (you may round off e,n to nearest 500m for example):

e|n
---|---
617288|6049781
617288|6050281
617288|6050781
617288|6051281
617288|6051781
