### ISSUE TITLE
Code for figure of estimates with se-intervals

### ISSUE THREAD

**Issue by thornoe** [abjer/tsds#30]
For Assignment 3 we were asked to comment on the following figure of estimates at different border values.
<img src="https://github.com/abjer/tsds/raw/master/material/10_spatial2/results_fig.png">

Could you share the code used as inspiration for creating similar figures?

**Comment by kristianolesenlarsen** [comment]
It is just a mix of scatter and line plots.

```python 
import matplotlib.pyplot as plt 
from numpy.random import randn

xvals = range(10)
means = [len(xvals) - i - randn() for i in xvals]
upper = [m + 1 for m in means]
lower = [m - 1 for m in means]

fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(xvals, means, color = 'black')
for x, low, high in zip(xvals, lower, upper):
    ax.plot([x,x], [low, high], color = 'black')
```
