### ISSUE TITLE
Installing hSBM/graph-tool

### ISSUE THREAD

**Issue by hzille** [abjer/tsds#33]
Hi everyone,

We are doing text analysis in our project and would like to use hSBM. However, we are struggling with getting it installed.

We followed the guide on 

https://buildmedia.readthedocs.org/media/pdf/topsbm/stable/topsbm.pdf

but encounter a problem with graph-tool, which fails to install during the hSBM installation. 

We were also looking at the installation instructions on the following site, but couldn't really make sense of it, since we do not know how the "configure/make/install" procedure works. 

https://git.skewed.de/count0/graph-tool/wikis/installation-instructions

We also attempted to install graph-tool seperately. We downloaded it from https://graph-tool.skewed.de/ but we do not know how to install it afterwards.

Any help would be more than welcomed.

**Comment by kristianolesenlarsen** [comment]
I think your best bets are either to run it in a docker container (lets see if we can get it working tomorrow) or installing it on a linux distribution, perhaps just as a virtual/cloud machine (which will probably still be a bit difficult to get working).

**Comment by kristianolesenlarsen** [comment]
Follow the instructions on installing graph-tool in a docker container here: https://git.skewed.de/count0/graph-tool/wikis/installation-instructions.

If you are on windows/(mac?) replace 0.0.0.0 with 127.0.0.1 in the url you get after running `jupyter notebook --ip 0.0.0.0` and you should get access to a notebook running in the container when you paste the url in your browser.
