### ISSUE TITLE
Trouble with torch

### ISSUE THREAD

**Issue by thaislaerkholmj** [abjer/tsds#8]
I have trouble getting torch to work and looking for some inspiration to fix this. 
Basically I have tried with and without cuda, - both before and after conda update --all:
`conda install pytorch-cpu torchvision-cpu -c pytorch`
`conda install pytorch torchvision cudatoolkit=9.0 -c pytorch`

When I write
`import torch`

I get
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-eb42ca6e4af3> in <module>
----> 1 import torch

~\Anaconda3\lib\site-packages\torch\__init__.py in <module>
     51         from ctypes.wintypes import DWORD, HMODULE
     52 
---> 53         AddDllDirectory = windll.kernel32.AddDllDirectory
     54         AddDllDirectory.restype = DWORD
     55         AddDllDirectory.argtypes = [c_wchar_p]

~\Anaconda3\lib\ctypes\__init__.py in __getattr__(self, name)
    367         if name.startswith('__') and name.endswith('__'):
    368             raise AttributeError(name)
--> 369         func = self.__getitem__(name)
    370         setattr(self, name, func)
    371         return func

~\Anaconda3\lib\ctypes\__init__.py in __getitem__(self, name_or_ordinal)
    372 
    373     def __getitem__(self, name_or_ordinal):
--> 374         func = self._FuncPtr((name_or_ordinal, self))
    375         if not isinstance(name_or_ordinal, int):
    376             func.__name__ = name_or_ordinal

AttributeError: function 'AddDllDirectory' not found
```

This post might be on to something, but I'm not sure I completely follow:
https://github.com/pytorch/pytorch/issues/17051

**Comment by kristianolesenlarsen** [comment]
You can only run the GPU version if you have a gpu card on your system, so the first step is to figure that out. This will determine if you should get the cpu version or not. 

Once you know what version to get, can you try removing pytorch and then installing it again using pip? [the correct commands can be found here](https://pytorch.org/get-started/locally/).

**Comment by thaislaerkholmj** [comment]
pip install works, thanks. Conda install made it fail in current build/version
