### ISSUE TITLE
Pipfile

### ISSUE THREAD

**Issue by jeppejohansen** [abjer/tsds#9]
Hey,

Is it possible to make a Pipfile or alternatively an requirements.txt file to ensure we have the right dependencies, in our local installation of python.

**Comment by abjer** [comment]
Do you have trouble installing a specific package? Have you tried install with `conda`; one of the advantages of `conda` is that handles possibly overlapping dependencies and can install packages with complex depencies.

**Comment by jeppejohansen** [comment]
Yes, 

I prefer not to use conda, because it alters the paths to root python. There is no problem with installations, mainly it's just so i can install all dependencies at once, and know they are the right versions. Pipfile ensures a deterministic build, which is why i would prefer that.
